<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/BalanceRefundInputMapper.map" md5sum="6bc7fb8990a1e0c0eda795d74ede164c" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		BalanceRefundInputMapper.map
*   Map declaration(s):	BalanceRefundInputMapper
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FMaintainAccessGC%257DcancelPolicyRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DinitiateBalanceRefund/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://Access-ApplicationGC"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in5="http://GCDomain-v1.0.0/org/tataaig/access/MaintainAccessGC"
    xmlns:in="http://RACASBO"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in2="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/MaintainAccessGC"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in4="http://GCLibrary/org/aig/access/BO"
    xmlns:in3="http://GCLibrary/org/aig/access/bo"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:out="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/BalanceRefundInputMapper"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io4:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:BalanceRefundInputMapper2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io4:smo" mode="map:BalanceRefundInputMapper">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io4:smo" to "io4:smo".  -->
  <xsl:template match="io4:smo"  mode="map:BalanceRefundInputMapper">
    <io4:smo>
      <context>
        <!-- a structural mapping: "context/correlation"(correlationBO) to "correlation"(correlationBO) -->
        <xsl:if test="context/correlation">
          <xsl:copy-of select="context/correlation"/>
        </xsl:if>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out2:initiateBalanceRefund'"/>
        </xsl:attribute>
        <out:initiateBalanceRefund>
          <!-- a simple data mapping: "body/in5:cancelPolicy/cancellationRefundInput/source"(string) to "out:source"(string) -->
          <xsl:if test="body/in5:cancelPolicy/cancellationRefundInput/source">
            <xsl:element name="out:source">
              <xsl:value-of select="body/in5:cancelPolicy/cancellationRefundInput/source"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in5:cancelPolicy/cancellationRefundInput/medium"(string) to "out:medium"(string) -->
          <xsl:if test="body/in5:cancelPolicy/cancellationRefundInput/medium">
            <xsl:element name="out:medium">
              <xsl:value-of select="body/in5:cancelPolicy/cancellationRefundInput/medium"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in5:cancelPolicy/cancellationRefundInput/campaign"(string) to "out:campaign"(string) -->
          <xsl:if test="body/in5:cancelPolicy/cancellationRefundInput/campaign">
            <xsl:element name="out:campaign">
              <xsl:value-of select="body/in5:cancelPolicy/cancellationRefundInput/campaign"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in5:cancelPolicy/cancPolicyData/policyNo"(string) to "out:policyNo"(string) -->
          <xsl:if test="body/in5:cancelPolicy/cancPolicyData/policyNo">
            <xsl:element name="out:policyNo">
              <xsl:value-of select="body/in5:cancelPolicy/cancPolicyData/policyNo"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in5:cancelPolicy/cancPolicyData/userId"(string) to "out:UserId"(string) -->
          <xsl:if test="body/in5:cancelPolicy/cancPolicyData/userId">
            <xsl:element name="out:UserId">
              <xsl:value-of select="body/in5:cancelPolicy/cancPolicyData/userId"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in5:cancelPolicy/cancPolicyData/remarks"(string) to "out:Remarks"(string) -->
          <xsl:if test="body/in5:cancelPolicy/cancPolicyData/remarks">
            <xsl:element name="out:Remarks">
              <xsl:value-of select="body/in5:cancelPolicy/cancPolicyData/remarks"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in5:cancelPolicy/cancPolicyData/certificateNumber"(string) to "out:CertificateNumber"(string) -->
          <xsl:if test="body/in5:cancelPolicy/cancPolicyData/certificateNumber">
            <xsl:element name="out:CertificateNumber">
              <xsl:value-of select="body/in5:cancelPolicy/cancPolicyData/certificateNumber"/>
            </xsl:element>
          </xsl:if>
        </out:initiateBalanceRefund>
      </body>
    </io4:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io4:smo" to "io4:smo".  -->
  <xsl:template name="map:BalanceRefundInputMapper2">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/correlation"(correlationBO) to "correlation"(correlationBO) -->
      <xsl:if test="$smo/context/correlation">
        <xsl:copy-of select="$smo/context/correlation"/>
      </xsl:if>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:initiateBalanceRefund'"/>
      </xsl:attribute>
      <out:initiateBalanceRefund>
        <!-- a simple data mapping: "$smo/body/in5:cancelPolicy/cancellationRefundInput/source"(string) to "out:source"(string) -->
        <xsl:if test="$smo/body/in5:cancelPolicy/cancellationRefundInput/source">
          <xsl:element name="out:source">
            <xsl:value-of select="$smo/body/in5:cancelPolicy/cancellationRefundInput/source"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in5:cancelPolicy/cancellationRefundInput/medium"(string) to "out:medium"(string) -->
        <xsl:if test="$smo/body/in5:cancelPolicy/cancellationRefundInput/medium">
          <xsl:element name="out:medium">
            <xsl:value-of select="$smo/body/in5:cancelPolicy/cancellationRefundInput/medium"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in5:cancelPolicy/cancellationRefundInput/campaign"(string) to "out:campaign"(string) -->
        <xsl:if test="$smo/body/in5:cancelPolicy/cancellationRefundInput/campaign">
          <xsl:element name="out:campaign">
            <xsl:value-of select="$smo/body/in5:cancelPolicy/cancellationRefundInput/campaign"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in5:cancelPolicy/cancPolicyData/policyNo"(string) to "out:policyNo"(string) -->
        <xsl:if test="$smo/body/in5:cancelPolicy/cancPolicyData/policyNo">
          <xsl:element name="out:policyNo">
            <xsl:value-of select="$smo/body/in5:cancelPolicy/cancPolicyData/policyNo"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in5:cancelPolicy/cancPolicyData/userId"(string) to "out:UserId"(string) -->
        <xsl:if test="$smo/body/in5:cancelPolicy/cancPolicyData/userId">
          <xsl:element name="out:UserId">
            <xsl:value-of select="$smo/body/in5:cancelPolicy/cancPolicyData/userId"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in5:cancelPolicy/cancPolicyData/remarks"(string) to "out:Remarks"(string) -->
        <xsl:if test="$smo/body/in5:cancelPolicy/cancPolicyData/remarks">
          <xsl:element name="out:Remarks">
            <xsl:value-of select="$smo/body/in5:cancelPolicy/cancPolicyData/remarks"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in5:cancelPolicy/cancPolicyData/certificateNumber"(string) to "out:CertificateNumber"(string) -->
        <xsl:if test="$smo/body/in5:cancelPolicy/cancPolicyData/certificateNumber">
          <xsl:element name="out:CertificateNumber">
            <xsl:value-of select="$smo/body/in5:cancelPolicy/cancPolicyData/certificateNumber"/>
          </xsl:element>
        </xsl:if>
      </out:initiateBalanceRefund>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
