<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/BalanceRefundInputMap.map" md5sum="e5bb898ae50278c07d93c20cd280516a" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		BalanceRefundInputMap.map
*   Map declaration(s):	BalanceRefundInputMap
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DgetProposalDetailsBalanceRefundRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DpolicyDetailsByProposalNo/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in5="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:in="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in2="http://RACASBO"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in4="http://GCLibrary/org/aig/access/BO"
    xmlns:in3="http://GCLibrary/org/aig/access/bo"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:out="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/BalanceRefundInputMap"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:policyDetailsByProposalNo'"/>
            </xsl:attribute>
            <xsl:call-template name="map:BalanceRefundInputMap2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:BalanceRefundInputMap">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:BalanceRefundInputMap">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:policyDetailsByProposalNo'"/>
      </xsl:attribute>
      <out:policyDetailsByProposalNo>
        <!-- a simple data mapping: "in:getProposalDetailsBalanceRefund/GCInputs/source"(string) to "out:source"(string) -->
        <xsl:if test="in:getProposalDetailsBalanceRefund/GCInputs/source">
          <xsl:element name="out:source">
            <xsl:value-of select="in:getProposalDetailsBalanceRefund/GCInputs/source"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in:getProposalDetailsBalanceRefund/GCInputs/medium"(string) to "out:medium"(string) -->
        <xsl:if test="in:getProposalDetailsBalanceRefund/GCInputs/medium">
          <xsl:element name="out:medium">
            <xsl:value-of select="in:getProposalDetailsBalanceRefund/GCInputs/medium"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in:getProposalDetailsBalanceRefund/GCInputs/campaign"(string) to "out:campaign"(string) -->
        <xsl:if test="in:getProposalDetailsBalanceRefund/GCInputs/campaign">
          <xsl:element name="out:campaign">
            <xsl:value-of select="in:getProposalDetailsBalanceRefund/GCInputs/campaign"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in:getProposalDetailsBalanceRefund/GCInputs/strServiceToken"(string) to "out:strServiceToken"(string) -->
        <xsl:if test="in:getProposalDetailsBalanceRefund/GCInputs/strServiceToken">
          <xsl:element name="out:strServiceToken">
            <xsl:value-of select="in:getProposalDetailsBalanceRefund/GCInputs/strServiceToken"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in:getProposalDetailsBalanceRefund/proposalNumber"(string) to "out:ProposalNo"(string) -->
        <xsl:if test="in:getProposalDetailsBalanceRefund/proposalNumber">
          <xsl:element name="out:ProposalNo">
            <xsl:value-of select="in:getProposalDetailsBalanceRefund/proposalNumber"/>
          </xsl:element>
        </xsl:if>
      </out:policyDetailsByProposalNo>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:BalanceRefundInputMap2">
    <xsl:param name="body"/>
    <out:policyDetailsByProposalNo>
      <!-- a simple data mapping: "$body/in:getProposalDetailsBalanceRefund/GCInputs/source"(string) to "out:source"(string) -->
      <xsl:if test="$body/in:getProposalDetailsBalanceRefund/GCInputs/source">
        <xsl:element name="out:source">
          <xsl:value-of select="$body/in:getProposalDetailsBalanceRefund/GCInputs/source"/>
        </xsl:element>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:getProposalDetailsBalanceRefund/GCInputs/medium"(string) to "out:medium"(string) -->
      <xsl:if test="$body/in:getProposalDetailsBalanceRefund/GCInputs/medium">
        <xsl:element name="out:medium">
          <xsl:value-of select="$body/in:getProposalDetailsBalanceRefund/GCInputs/medium"/>
        </xsl:element>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:getProposalDetailsBalanceRefund/GCInputs/campaign"(string) to "out:campaign"(string) -->
      <xsl:if test="$body/in:getProposalDetailsBalanceRefund/GCInputs/campaign">
        <xsl:element name="out:campaign">
          <xsl:value-of select="$body/in:getProposalDetailsBalanceRefund/GCInputs/campaign"/>
        </xsl:element>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:getProposalDetailsBalanceRefund/GCInputs/strServiceToken"(string) to "out:strServiceToken"(string) -->
      <xsl:if test="$body/in:getProposalDetailsBalanceRefund/GCInputs/strServiceToken">
        <xsl:element name="out:strServiceToken">
          <xsl:value-of select="$body/in:getProposalDetailsBalanceRefund/GCInputs/strServiceToken"/>
        </xsl:element>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:getProposalDetailsBalanceRefund/proposalNumber"(string) to "out:ProposalNo"(string) -->
      <xsl:if test="$body/in:getProposalDetailsBalanceRefund/proposalNumber">
        <xsl:element name="out:ProposalNo">
          <xsl:value-of select="$body/in:getProposalDetailsBalanceRefund/proposalNumber"/>
        </xsl:element>
      </xsl:if>
    </out:policyDetailsByProposalNo>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
