<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/calculatePremium_MarineCargo_InputMap_req_1.map" md5sum="83f62b1b970501acfd8d3b01e88b38dc" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		calculatePremium_MarineCargo_InputMap_req_1.map
*   Map declaration(s):	calculatePremium_MarineCargo_InputMap_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DcalculateCancellationRefundRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASMarineService%252F%257DwebServicePremiumCalculationMarine/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in2="http://GCLibrary/org/aig/access/BO"
    xmlns:in4="http://RACASBO"
    xmlns:in3="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:io7="http://Access-ApplicationGC"
    xmlns:in5="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:in="http://GCLibrary/org/aig/access/bo"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out3="wsdl.http://stub.tagicesb.com/wsdl/RASMarineService/"
    xmlns:out2="http://stub.tagicesb.com/wsdl/RASMarineService/"
    xmlns:out="WebService_RefundCancellationMarine"
    xmlns:map="http://Access-ApplicationGC/xslt/calculatePremium_MarineCargo_InputMap_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:calculatePremium_MarineCargo_InputMap_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:calculatePremium_MarineCargo_InputMap_req_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:calculatePremium_MarineCargo_InputMap_req_1">
    <io2:smo>
      <context>
        <!-- a structural mapping: "context/correlation"(correlationBO) to "correlation"(correlationBO) -->
        <xsl:if test="context/correlation">
          <xsl:copy-of select="context/correlation"/>
        </xsl:if>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out3:webServicePremiumCalculationMarine'"/>
        </xsl:attribute>
        <out2:webServicePremiumCalculationMarine>
          <!-- a simple data mapping: "body/in3:calculateCancellationRefund/cancellationRefundInput/source"(string) to "out2:source"(string) -->
          <xsl:if test="body/in3:calculateCancellationRefund/cancellationRefundInput/source">
            <xsl:element name="out2:source">
              <xsl:value-of select="body/in3:calculateCancellationRefund/cancellationRefundInput/source"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in3:calculateCancellationRefund/cancellationRefundInput/medium"(string) to "out2:medium"(string) -->
          <xsl:if test="body/in3:calculateCancellationRefund/cancellationRefundInput/medium">
            <xsl:element name="out2:medium">
              <xsl:value-of select="body/in3:calculateCancellationRefund/cancellationRefundInput/medium"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in3:calculateCancellationRefund/cancellationRefundInput/campaign"(string) to "out2:campaign"(string) -->
          <xsl:if test="body/in3:calculateCancellationRefund/cancellationRefundInput/campaign">
            <xsl:element name="out2:campaign">
              <xsl:value-of select="body/in3:calculateCancellationRefund/cancellationRefundInput/campaign"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in3:calculateCancellationRefund/cancellationRefundInput/strServiceToken"(string) to "out2:strServiceToken"(string) -->
          <xsl:if test="body/in3:calculateCancellationRefund/cancellationRefundInput/strServiceToken">
            <xsl:element name="out2:strServiceToken">
              <xsl:value-of select="body/in3:calculateCancellationRefund/cancellationRefundInput/strServiceToken"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/userId"(string) to "out2:UserId"(string) -->
          <xsl:if test="body/in3:calculateCancellationRefund/input/userId">
            <xsl:element name="out2:UserId">
              <xsl:value-of select="body/in3:calculateCancellationRefund/input/userId"/>
            </xsl:element>
          </xsl:if>
          <out2:RefundCancellation>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/policyNo"(string) to "out:PolicyNo"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/policyNo">
              <xsl:element name="out:PolicyNo">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/policyNo"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/proposalNo"(string) to "out:ProposalNo"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/proposalNo">
              <xsl:element name="out:ProposalNo">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/proposalNo"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/product"(string) to "out:ProductCode"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/product">
              <xsl:element name="out:ProductCode">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/product"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/refundAmount"(string) to "out:RefundAmount"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/refundAmount">
              <xsl:element name="out:RefundAmount">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/refundAmount"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "context/correlation/endDateOfRequest"(string) to "out:EndDateOfRequest"(string) -->
            <xsl:if test="context/correlation/endDateOfRequest">
              <xsl:element name="out:EndDateOfRequest">
                <xsl:value-of select="context/correlation/endDateOfRequest"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "context/correlation/effectiveDate"(string) to "out:MTAEffDate"(string) -->
            <xsl:if test="context/correlation/effectiveDate">
              <xsl:element name="out:MTAEffDate">
                <xsl:value-of select="context/correlation/effectiveDate"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/effectiveTime"(string) to "out:MTAEffTime"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/effectiveTime">
              <xsl:element name="out:MTAEffTime">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/effectiveTime"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/cancellationReason"(string) to "out:ReasonforCanc"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/cancellationReason">
              <xsl:element name="out:ReasonforCanc">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/cancellationReason"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/cancellationDescription"(string) to "out:DescofCancReason"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/cancellationDescription">
              <xsl:element name="out:DescofCancReason">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/cancellationDescription"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/cancellationOption"(string) to "out:OptionforCancofInsurance"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/cancellationOption">
              <xsl:element name="out:OptionforCancofInsurance">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/cancellationOption"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in3:calculateCancellationRefund/input/remarks"(string) to "out:Remarks"(string) -->
            <xsl:if test="body/in3:calculateCancellationRefund/input/remarks">
              <xsl:element name="out:Remarks">
                <xsl:value-of select="body/in3:calculateCancellationRefund/input/remarks"/>
              </xsl:element>
            </xsl:if>
          </out2:RefundCancellation>
        </out2:webServicePremiumCalculationMarine>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:calculatePremium_MarineCargo_InputMap_req_12">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/correlation"(correlationBO) to "correlation"(correlationBO) -->
      <xsl:if test="$smo/context/correlation">
        <xsl:copy-of select="$smo/context/correlation"/>
      </xsl:if>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:webServicePremiumCalculationMarine'"/>
      </xsl:attribute>
      <out2:webServicePremiumCalculationMarine>
        <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/source"(string) to "out2:source"(string) -->
        <xsl:if test="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/source">
          <xsl:element name="out2:source">
            <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/source"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/medium"(string) to "out2:medium"(string) -->
        <xsl:if test="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/medium">
          <xsl:element name="out2:medium">
            <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/medium"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/campaign"(string) to "out2:campaign"(string) -->
        <xsl:if test="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/campaign">
          <xsl:element name="out2:campaign">
            <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/campaign"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/strServiceToken"(string) to "out2:strServiceToken"(string) -->
        <xsl:if test="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/strServiceToken">
          <xsl:element name="out2:strServiceToken">
            <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/cancellationRefundInput/strServiceToken"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/userId"(string) to "out2:UserId"(string) -->
        <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/userId">
          <xsl:element name="out2:UserId">
            <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/userId"/>
          </xsl:element>
        </xsl:if>
        <out2:RefundCancellation>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/policyNo"(string) to "out:PolicyNo"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/policyNo">
            <xsl:element name="out:PolicyNo">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/policyNo"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/proposalNo"(string) to "out:ProposalNo"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/proposalNo">
            <xsl:element name="out:ProposalNo">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/proposalNo"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/product"(string) to "out:ProductCode"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/product">
            <xsl:element name="out:ProductCode">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/product"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/refundAmount"(string) to "out:RefundAmount"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/refundAmount">
            <xsl:element name="out:RefundAmount">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/refundAmount"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/context/correlation/endDateOfRequest"(string) to "out:EndDateOfRequest"(string) -->
          <xsl:if test="$smo/context/correlation/endDateOfRequest">
            <xsl:element name="out:EndDateOfRequest">
              <xsl:value-of select="$smo/context/correlation/endDateOfRequest"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/context/correlation/effectiveDate"(string) to "out:MTAEffDate"(string) -->
          <xsl:if test="$smo/context/correlation/effectiveDate">
            <xsl:element name="out:MTAEffDate">
              <xsl:value-of select="$smo/context/correlation/effectiveDate"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/effectiveTime"(string) to "out:MTAEffTime"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/effectiveTime">
            <xsl:element name="out:MTAEffTime">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/effectiveTime"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/cancellationReason"(string) to "out:ReasonforCanc"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/cancellationReason">
            <xsl:element name="out:ReasonforCanc">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/cancellationReason"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/cancellationDescription"(string) to "out:DescofCancReason"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/cancellationDescription">
            <xsl:element name="out:DescofCancReason">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/cancellationDescription"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/cancellationOption"(string) to "out:OptionforCancofInsurance"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/cancellationOption">
            <xsl:element name="out:OptionforCancofInsurance">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/cancellationOption"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in3:calculateCancellationRefund/input/remarks"(string) to "out:Remarks"(string) -->
          <xsl:if test="$smo/body/in3:calculateCancellationRefund/input/remarks">
            <xsl:element name="out:Remarks">
              <xsl:value-of select="$smo/body/in3:calculateCancellationRefund/input/remarks"/>
            </xsl:element>
          </xsl:if>
        </out2:RefundCancellation>
      </out2:webServicePremiumCalculationMarine>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
