<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/CalculatePremium_Khokha_Input.map" md5sum="1b9e1d8233c3a5eca56b95ac10994d4b" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		CalculatePremium_Khokha_Input.map
*   Map declaration(s):	CalculatePremium_Khokha_Input
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DcalculateCancellationRefundRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252Fstub.unotechsoft.com%252Fwsdl%252FRASRefundCancellationKhoka%252F%257DwebServiceRASGenericPremiumCalculation/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://Access-ApplicationGC"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in5="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:in="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in2="http://RACASBO"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in4="http://GCLibrary/org/aig/access/BO"
    xmlns:in3="http://GCLibrary/org/aig/access/bo"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="wsdl.http://stub.unotechsoft.com/wsdl/RASRefundCancellationKhoka/"
    xmlns:out="http://stub.unotechsoft.com/wsdl/RASRefundCancellationKhoka/"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/CalculatePremium_Khokha_Input"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io4:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:CalculatePremium_Khokha_Input2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io4:smo" mode="map:CalculatePremium_Khokha_Input">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io4:smo" to "io4:smo".  -->
  <xsl:template match="io4:smo"  mode="map:CalculatePremium_Khokha_Input">
    <io4:smo>
      <context>
        <!-- a structural mapping: "context/correlation"(correlationBO) to "correlation"(correlationBO) -->
        <xsl:if test="context/correlation">
          <xsl:copy-of select="context/correlation"/>
        </xsl:if>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out2:webServiceRASGenericPremiumCalculation'"/>
        </xsl:attribute>
        <out:webServiceRASGenericPremiumCalculation>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/cancellationRefundInput/source"(string) to "out:source"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/cancellationRefundInput/source">
            <xsl:element name="out:source">
              <xsl:value-of select="body/in:calculateCancellationRefund/cancellationRefundInput/source"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/cancellationRefundInput/medium"(string) to "out:medium"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/cancellationRefundInput/medium">
            <xsl:element name="out:medium">
              <xsl:value-of select="body/in:calculateCancellationRefund/cancellationRefundInput/medium"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/cancellationRefundInput/campaign"(string) to "out:campaign"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/cancellationRefundInput/campaign">
            <xsl:element name="out:campaign">
              <xsl:value-of select="body/in:calculateCancellationRefund/cancellationRefundInput/campaign"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple mapping with no associated source:  to "out:strServiceToken"(string) -->
          <xsl:element name="out:strServiceToken">
            <xsl:text></xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/policyNo"(string) to "out:iPolicyNo"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/policyNo">
            <xsl:element name="out:iPolicyNo">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/policyNo"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/proposalNo"(string) to "out:iReferenceNo"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/proposalNo">
            <xsl:element name="out:iReferenceNo">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/proposalNo"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/product"(string) to "out:iProductCode"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/product">
            <xsl:element name="out:iProductCode">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/product"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/endDateOfRequest"(string) to "out:iEndDatOfRequest"(string) -->
          <xsl:if test="context/correlation/endDateOfRequest">
            <xsl:element name="out:iEndDatOfRequest">
              <xsl:value-of select="context/correlation/endDateOfRequest"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/effectiveDate"(string) to "out:iMtaeffDate"(string) -->
          <xsl:if test="context/correlation/effectiveDate">
            <xsl:element name="out:iMtaeffDate">
              <xsl:value-of select="context/correlation/effectiveDate"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/effectiveTime"(string) to "out:iMtaeffTime"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/effectiveTime">
            <xsl:element name="out:iMtaeffTime">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/effectiveTime"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/cancellationReason"(string) to "out:iReasonForCanc"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/cancellationReason">
            <xsl:element name="out:iReasonForCanc">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/cancellationReason"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/cancellationDescription"(string) to "out:iDescofCancReason"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/cancellationDescription">
            <xsl:element name="out:iDescofCancReason">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/cancellationDescription"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/cancellationOption"(string) to "out:iOptionforCancofInsurance"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/cancellationOption">
            <xsl:element name="out:iOptionforCancofInsurance">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/cancellationOption"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "body/in:calculateCancellationRefund/input/remarks"(string) to "out:iRemarks"(string) -->
          <xsl:if test="body/in:calculateCancellationRefund/input/remarks">
            <xsl:element name="out:iRemarks">
              <xsl:value-of select="body/in:calculateCancellationRefund/input/remarks"/>
            </xsl:element>
          </xsl:if>
        </out:webServiceRASGenericPremiumCalculation>
      </body>
    </io4:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io4:smo" to "io4:smo".  -->
  <xsl:template name="map:CalculatePremium_Khokha_Input2">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/correlation"(correlationBO) to "correlation"(correlationBO) -->
      <xsl:if test="$smo/context/correlation">
        <xsl:copy-of select="$smo/context/correlation"/>
      </xsl:if>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:webServiceRASGenericPremiumCalculation'"/>
      </xsl:attribute>
      <out:webServiceRASGenericPremiumCalculation>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/cancellationRefundInput/source"(string) to "out:source"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/cancellationRefundInput/source">
          <xsl:element name="out:source">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/cancellationRefundInput/source"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/cancellationRefundInput/medium"(string) to "out:medium"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/cancellationRefundInput/medium">
          <xsl:element name="out:medium">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/cancellationRefundInput/medium"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/cancellationRefundInput/campaign"(string) to "out:campaign"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/cancellationRefundInput/campaign">
          <xsl:element name="out:campaign">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/cancellationRefundInput/campaign"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple mapping with no associated source:  to "out:strServiceToken"(string) -->
        <xsl:element name="out:strServiceToken">
          <xsl:text></xsl:text>
        </xsl:element>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/policyNo"(string) to "out:iPolicyNo"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/policyNo">
          <xsl:element name="out:iPolicyNo">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/policyNo"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/proposalNo"(string) to "out:iReferenceNo"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/proposalNo">
          <xsl:element name="out:iReferenceNo">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/proposalNo"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/product"(string) to "out:iProductCode"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/product">
          <xsl:element name="out:iProductCode">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/product"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/endDateOfRequest"(string) to "out:iEndDatOfRequest"(string) -->
        <xsl:if test="$smo/context/correlation/endDateOfRequest">
          <xsl:element name="out:iEndDatOfRequest">
            <xsl:value-of select="$smo/context/correlation/endDateOfRequest"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/effectiveDate"(string) to "out:iMtaeffDate"(string) -->
        <xsl:if test="$smo/context/correlation/effectiveDate">
          <xsl:element name="out:iMtaeffDate">
            <xsl:value-of select="$smo/context/correlation/effectiveDate"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/effectiveTime"(string) to "out:iMtaeffTime"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/effectiveTime">
          <xsl:element name="out:iMtaeffTime">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/effectiveTime"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/cancellationReason"(string) to "out:iReasonForCanc"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/cancellationReason">
          <xsl:element name="out:iReasonForCanc">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/cancellationReason"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/cancellationDescription"(string) to "out:iDescofCancReason"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/cancellationDescription">
          <xsl:element name="out:iDescofCancReason">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/cancellationDescription"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/cancellationOption"(string) to "out:iOptionforCancofInsurance"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/cancellationOption">
          <xsl:element name="out:iOptionforCancofInsurance">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/cancellationOption"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/body/in:calculateCancellationRefund/input/remarks"(string) to "out:iRemarks"(string) -->
        <xsl:if test="$smo/body/in:calculateCancellationRefund/input/remarks">
          <xsl:element name="out:iRemarks">
            <xsl:value-of select="$smo/body/in:calculateCancellationRefund/input/remarks"/>
          </xsl:element>
        </xsl:if>
      </out:webServiceRASGenericPremiumCalculation>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
