<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/cancelPolicy_Response_res_1.map" md5sum="2f829ceaf362c81e0cc9bb2d66647dea" version="8.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		cancelPolicy_Response_res_1.map
*   Map declaration(s):	cancelPolicy_Response_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257BWebService_RefundCancellationDtls%257DWebService_RefundCancellationDtlsSoapOut/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FMaintainAccessGC%257DcancelPolicyResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:math="http://exslt.org/math"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:exsl="http://exslt.org/common"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:in2="WebService_RefundCancellationDtls"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:in="wsdl.WebService_RefundCancellationDtls"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out3="http://RACASBO"
    xmlns:out2="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/MaintainAccessGC"
    xmlns:out4="http://GCLibrary/org/aig/access/BO"
    xmlns:out="http://GCDomain-v1.0.0/org/tataaig/access/MaintainAccessGC"
    xmlns:out5="http://GCLibrary/org/aig/access/bo"
    xmlns:map="http://Access-ApplicationGC/xslt/cancelPolicy_Response_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="math str set date exsl map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:cancelPolicyResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:cancelPolicy_Response_res_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:cancelPolicy_Response_res_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:cancelPolicy_Response_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:cancelPolicyResponseMsg'"/>
      </xsl:attribute>
      <out:cancelPolicyResponse>
        <cancelPolicyStatus>
          <!-- a simple data mapping: "in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalStatus"(string) to "out3:status"(string) -->
          <xsl:if test="in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalStatus">
            <xsl:element name="out3:status">
              <xsl:value-of select="in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalStatus"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalNo"(string) to "out3:data"(string) -->
          <xsl:if test="in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalNo">
            <xsl:element name="out3:data">
              <xsl:value-of select="in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalNo"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ErrorDesc"(string) to "out3:message"(string) -->
          <xsl:if test="in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ErrorDesc">
            <xsl:element name="out3:message">
              <xsl:value-of select="in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ErrorDesc"/>
            </xsl:element>
          </xsl:if>
        </cancelPolicyStatus>
      </out:cancelPolicyResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:cancelPolicy_Response_res_12">
    <xsl:param name="body"/>
    <out:cancelPolicyResponse>
      <cancelPolicyStatus>
        <!-- a simple data mapping: "$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalStatus"(string) to "out3:status"(string) -->
        <xsl:if test="$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalStatus">
          <xsl:element name="out3:status">
            <xsl:value-of select="$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalStatus"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalNo"(string) to "out3:data"(string) -->
        <xsl:if test="$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalNo">
          <xsl:element name="out3:data">
            <xsl:value-of select="$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ProposalNo"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ErrorDesc"(string) to "out3:message"(string) -->
        <xsl:if test="$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ErrorDesc">
          <xsl:element name="out3:message">
            <xsl:value-of select="$body/in2:WebService_RefundCancellationDtlsResponse/in2:WebService_RefundCancellationDtlsResult/in2:ErrorDesc"/>
          </xsl:element>
        </xsl:if>
      </cancelPolicyStatus>
    </out:cancelPolicyResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
