<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/fetchPropReceiptsRASDetailsOutputMap.map" md5sum="97f2a9e3f51925a2e115ebfeb65c07ae" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		fetchPropReceiptsRASDetailsOutputMap.map
*   Map declaration(s):	fetchPropReceiptsRASDetailsOutputMap
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DfetchPropReceiptsRASResponse/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DfetchPropReceiptsRASDetailsResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in6="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:io6="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:in5="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:in="WebService_AccRefundRequest"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in2="http://stub.tagicesb.com/wsdl/RASHealthService/"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io5="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in4="WebService_RefundCancellationDtls"
    xmlns:io4="http://www.w3.org/2005/08/addressing"
    xmlns:in3="WebService_RefundDetails"
    xmlns:out2="http://RACASBO"
    xmlns:out3="http://GCLibrary/org/aig/access/BO"
    xmlns:out4="http://GCLibrary/org/aig/access/bo"
    xmlns:out5="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/fetchPropReceiptsRASDetailsOutputMap"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out5:fetchPropReceiptsRASDetailsResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:fetchPropReceiptsRASDetailsOutputMap2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:fetchPropReceiptsRASDetailsOutputMap">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:fetchPropReceiptsRASDetailsOutputMap">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out5:fetchPropReceiptsRASDetailsResponseMsg'"/>
      </xsl:attribute>
      <out:fetchPropReceiptsRASDetailsResponse>
        <PropReceiptsRASDetails>
          <!-- a for-each transform: "paymentDetails"(FetchPropReceiptsRASDataResponse) to "out2:NilEndorsementReceiptDetailsList"(NilEndorsementReceiptDetails) -->
          <xsl:apply-templates select="in5:fetchPropReceiptsRASResponse/in5:FetchPropReceiptsRASResult/paymentDetails" mode="localPaymentDetailsToNilEndorsementReceiptDetailsList_1759979297">
          </xsl:apply-templates>
        </PropReceiptsRASDetails>
      </out:fetchPropReceiptsRASDetailsResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:fetchPropReceiptsRASDetailsOutputMap2">
    <xsl:param name="body"/>
    <out:fetchPropReceiptsRASDetailsResponse>
      <PropReceiptsRASDetails>
        <!-- a for-each transform: "paymentDetails"(FetchPropReceiptsRASDataResponse) to "out2:NilEndorsementReceiptDetailsList"(NilEndorsementReceiptDetails) -->
        <xsl:apply-templates select="$body/in5:fetchPropReceiptsRASResponse/in5:FetchPropReceiptsRASResult/paymentDetails" mode="localPaymentDetailsToNilEndorsementReceiptDetailsList_1759979297">
        </xsl:apply-templates>
      </PropReceiptsRASDetails>
    </out:fetchPropReceiptsRASDetailsResponse>
  </xsl:template>

  <!-- This rule represents a for-each transform: "paymentDetails" to "out2:NilEndorsementReceiptDetailsList".  -->
  <xsl:template match="paymentDetails"  mode="localPaymentDetailsToNilEndorsementReceiptDetailsList_1759979297">
    <out2:NilEndorsementReceiptDetailsList>
      <!-- a simple data mapping: "policyNo"(string) to "out2:policyNo"(string) -->
      <xsl:if test="policyNo">
        <out2:policyNo>
          <xsl:value-of select="policyNo"/>
        </out2:policyNo>
      </xsl:if>
      <!-- a simple data mapping: "proposalNo"(string) to "out2:proposalNo"(string) -->
      <xsl:if test="proposalNo">
        <out2:proposalNo>
          <xsl:value-of select="proposalNo"/>
        </out2:proposalNo>
      </xsl:if>
      <!-- a simple data mapping: "receiptNo"(string) to "out2:receiptNo"(string) -->
      <xsl:if test="receiptNo">
        <out2:receiptNo>
          <xsl:value-of select="receiptNo"/>
        </out2:receiptNo>
      </xsl:if>
      <!-- a simple data mapping: "subReceiptNo"(string) to "out2:subReceiptNo"(string) -->
      <xsl:if test="subReceiptNo">
        <out2:subReceiptNo>
          <xsl:value-of select="subReceiptNo"/>
        </out2:subReceiptNo>
      </xsl:if>
      <!-- a simple data mapping: "payerName"(string) to "out2:payerName"(string) -->
      <xsl:if test="payerName">
        <out2:payerName>
          <xsl:value-of select="payerName"/>
        </out2:payerName>
      </xsl:if>
      <!-- a simple data mapping: "receiptAmount"(string) to "out2:receiptAmount"(string) -->
      <xsl:if test="receiptAmount">
        <out2:receiptAmount>
          <xsl:value-of select="receiptAmount"/>
        </out2:receiptAmount>
      </xsl:if>
      <!-- a simple data mapping: "receiptDate"(string) to "out2:receiptDate"(string) -->
      <xsl:if test="receiptDate">
        <out2:receiptDate>
          <xsl:value-of select="receiptDate"/>
        </out2:receiptDate>
      </xsl:if>
    </out2:NilEndorsementReceiptDetailsList>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
