<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/find_RefundStatus_FaultMap_res_1.map" md5sum="a72ebedecb47fcf0a0d12c4adeba9476" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		find_RefundStatus_FaultMap_res_1.map
*   Map declaration(s):	find_RefundStatus_FaultMap_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DrefundRequestStatusResponse/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DfindRefundStatus_findRefundStatusFaultMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in2="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:in3="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:io5="http://www.w3.org/2005/08/addressing"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://Access-ApplicationGC"
    xmlns:io7="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in="WebService_RefundDetails"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out3="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out2="http://GCLibrary/org/aig/access/BO"
    xmlns:out5="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out4="http://RACASBO"
    xmlns:out="http://GCLibrary/org/aig/access/bo"
    xmlns:map="http://Access-ApplicationGC/xslt/find_RefundStatus_FaultMap_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:find_RefundStatus_FaultMap_res_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:find_RefundStatus_FaultMap_res_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:find_RefundStatus_FaultMap_res_1">
    <io2:smo>
      <context>
        <!-- a structural mapping: "context/correlation"(correlationBO) to "correlation"(correlationBO) -->
        <xsl:if test="context/correlation">
          <xsl:copy-of select="context/correlation"/>
        </xsl:if>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out5:findRefundStatus_findRefundStatusFaultMsg'"/>
        </xsl:attribute>
        <out3:findRefundStatusFault1_findRefundStatusFault>
          <!-- a simple data mapping: "body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:Status"(string) to "out4:status"(string) -->
          <xsl:if test="body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:Status">
            <xsl:element name="out4:status">
              <xsl:value-of select="body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:Status"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "context/correlation/request"(string) to "out4:data"(string) -->
          <xsl:if test="context/correlation/request">
            <xsl:element name="out4:data">
              <xsl:value-of select="context/correlation/request"/>
            </xsl:element>
          </xsl:if>
          <out4:error>
            <!-- a simple data mapping: "body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorID"(string) to "out4:errorCode"(string) -->
            <xsl:if test="body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorID">
              <xsl:element name="out4:errorCode">
                <xsl:value-of select="body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorID"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple mapping with no associated source:  to "out4:message"(string) -->
            <xsl:element name="out4:message">
              <xsl:text>Refund Request Status Failed</xsl:text>
            </xsl:element>
            <!-- a simple data mapping: "body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorDesc"(string) to "out4:errorDetail"(string) -->
            <xsl:if test="body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorDesc">
              <xsl:element name="out4:errorDetail">
                <xsl:value-of select="body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorDesc"/>
              </xsl:element>
            </xsl:if>
          </out4:error>
        </out3:findRefundStatusFault1_findRefundStatusFault>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:find_RefundStatus_FaultMap_res_12">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/correlation"(correlationBO) to "correlation"(correlationBO) -->
      <xsl:if test="$smo/context/correlation">
        <xsl:copy-of select="$smo/context/correlation"/>
      </xsl:if>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out5:findRefundStatus_findRefundStatusFaultMsg'"/>
      </xsl:attribute>
      <out3:findRefundStatusFault1_findRefundStatusFault>
        <!-- a simple data mapping: "$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:Status"(string) to "out4:status"(string) -->
        <xsl:if test="$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:Status">
          <xsl:element name="out4:status">
            <xsl:value-of select="$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:Status"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$smo/context/correlation/request"(string) to "out4:data"(string) -->
        <xsl:if test="$smo/context/correlation/request">
          <xsl:element name="out4:data">
            <xsl:value-of select="$smo/context/correlation/request"/>
          </xsl:element>
        </xsl:if>
        <out4:error>
          <!-- a simple data mapping: "$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorID"(string) to "out4:errorCode"(string) -->
          <xsl:if test="$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorID">
            <xsl:element name="out4:errorCode">
              <xsl:value-of select="$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorID"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple mapping with no associated source:  to "out4:message"(string) -->
          <xsl:element name="out4:message">
            <xsl:text>Refund Request Status Failed</xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorDesc"(string) to "out4:errorDetail"(string) -->
          <xsl:if test="$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorDesc">
            <xsl:element name="out4:errorDetail">
              <xsl:value-of select="$smo/body/in3:refundRequestStatusResponse/in:RefundRequestStatusResponse/in:RefundRequestStatusResult/in:RefundRequestStatus[1]/in:ErrorDesc"/>
            </xsl:element>
          </xsl:if>
        </out4:error>
      </out3:findRefundStatusFault1_findRefundStatusFault>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
