<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/find_Proposals_FaultMap_res_1.map" md5sum="7b7f949067db10ba46c6d52537c5966a" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		find_Proposals_FaultMap_res_1.map
*   Map declaration(s):	find_Proposals_FaultMap_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DproposalDetailsResponse/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DfindProposals_findProposalsFaultMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in2="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:in3="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:in="WebService_RefundDetails"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out3="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out2="http://RACASBO"
    xmlns:out5="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out4="http://GCLibrary/org/aig/access/BO"
    xmlns:out="http://GCLibrary/org/aig/access/bo"
    xmlns:map="http://Access-ApplicationGC/xslt/find_Proposals_FaultMap_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math str map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out3:findProposals_findProposalsFaultMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:find_Proposals_FaultMap_res_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:find_Proposals_FaultMap_res_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:find_Proposals_FaultMap_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:findProposals_findProposalsFaultMsg'"/>
      </xsl:attribute>
      <out5:findProposalsFault1_findProposalsFault>
        <!-- a simple data mapping: "in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:Status"(string) to "out2:status"(string) -->
        <xsl:if test="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:Status">
          <xsl:element name="out2:status">
            <xsl:value-of select="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:Status"/>
          </xsl:element>
        </xsl:if>
        <out2:error>
          <!-- a simple data mapping: "in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorID"(string) to "out2:errorCode"(string) -->
          <xsl:if test="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorID">
            <xsl:element name="out2:errorCode">
              <xsl:value-of select="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorID"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorDesc"(string) to "out2:message"(string) -->
          <!-- variables for custom code -->
          <xsl:variable name="ErrorDesc1" select="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorDesc"/>
          <xsl:if test="$ErrorDesc1[not(contains(text(),&apos;Please provide correct&apos;))]">
            <xsl:element name="out2:message">
              <xsl:value-of select="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorDesc"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails/in:PolicyNo"(string) to "out2:message"(string) -->
          <!-- variables for custom code -->
          <xsl:variable name="PolicyNo" select="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails/in:PolicyNo"/>
          <xsl:variable name="ErrorDesc" select="in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails/in:ErrorDesc"/>
          <xsl:if test="$ErrorDesc[contains(text(),&apos;Please provide correct&apos;)]">
            <xsl:element name="out2:message">
              <xsl:value-of select="str:concat((&quot;No Data Found For Policy No :&quot;,&quot; &quot;,$PolicyNo,&quot;. &quot;,$ErrorDesc))"/>
            </xsl:element>
          </xsl:if>
        </out2:error>
      </out5:findProposalsFault1_findProposalsFault>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:find_Proposals_FaultMap_res_12">
    <xsl:param name="body"/>
    <out5:findProposalsFault1_findProposalsFault>
      <!-- a simple data mapping: "$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:Status"(string) to "out2:status"(string) -->
      <xsl:if test="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:Status">
        <xsl:element name="out2:status">
          <xsl:value-of select="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:Status"/>
        </xsl:element>
      </xsl:if>
      <out2:error>
        <!-- a simple data mapping: "$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorID"(string) to "out2:errorCode"(string) -->
        <xsl:if test="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorID">
          <xsl:element name="out2:errorCode">
            <xsl:value-of select="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorID"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorDesc"(string) to "out2:message"(string) -->
        <!-- variables for custom code -->
        <xsl:variable name="ErrorDesc1" select="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorDesc"/>
        <xsl:if test="$ErrorDesc1[not(contains(text(),&apos;Please provide correct&apos;))]">
          <xsl:element name="out2:message">
            <xsl:value-of select="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails[1]/in:ErrorDesc"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails/in:PolicyNo"(string) to "out2:message"(string) -->
        <!-- variables for custom code -->
        <xsl:variable name="PolicyNo" select="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails/in:PolicyNo"/>
        <xsl:variable name="ErrorDesc" select="$body/in3:proposalDetailsResponse/in:ProposalDetailsResponse/in:ProposalDetailsResult/in:ProposalDetails/in:ErrorDesc"/>
        <xsl:if test="$ErrorDesc[contains(text(),&apos;Please provide correct&apos;)]">
          <xsl:element name="out2:message">
            <xsl:value-of select="str:concat((&quot;No Data Found For Policy No :&quot;,&quot; &quot;,$PolicyNo,&quot;. &quot;,$ErrorDesc))"/>
          </xsl:element>
        </xsl:if>
      </out2:error>
    </out5:findProposalsFault1_findProposalsFault>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
