<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/GCTransactionLogRequestMap_req_1.map" md5sum="5aacfdc444594780b2275c278c4a2328" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		GCTransactionLogRequestMap_req_1.map
*   Map declaration(s):	GCTransactionLogRequestMap_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252FGCLibrary%252Forg%252Faig%252Faccess%252FUpdateGCTransactionLog%257DupdateGCTransactionLogRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:io7="http://Access-ApplicationGC"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out3="wsdl.http://GCLibrary/org/aig/access/UpdateGCTransactionLog"
    xmlns:out2="http://GCLibrary/org/aig/access/bo"
    xmlns:out="http://GCLibrary/org/aig/access/UpdateGCTransactionLog"
    xmlns:map="http://Access-ApplicationGC/xslt/GCTransactionLogRequestMap_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:GCTransactionLogRequestMap_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:GCTransactionLogRequestMap_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:GCTransactionLogRequestMap_req_1">
    <io2:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out3:updateGCTransactionLogRequestMsg'"/>
        </xsl:attribute>
        <out:updateGCTransactionLog>
          <transactionLogRequest>
            <!-- a simple data mapping: "context/correlation/transactionId"(int) to "transactionId"(int) -->
            <xsl:if test="context/correlation/transactionId">
              <xsl:element name="transactionId">
                <xsl:value-of select="context/correlation/transactionId"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "context/correlation/request"(string) to "request"(string) -->
            <xsl:if test="context/correlation/request">
              <xsl:element name="request">
                <xsl:value-of select="context/correlation/request"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "context/correlation/isExecuting"(int) to "isExecuting"(int) -->
            <xsl:if test="context/correlation/isExecuting">
              <xsl:element name="isExecuting">
                <xsl:value-of select="context/correlation/isExecuting"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "context/correlation/lastRequestedOn"(dateTime) to "lastRequestedOn"(dateTime) -->
            <xsl:if test="context/correlation/lastRequestedOn">
              <xsl:element name="lastRequestedOn">
                <xsl:value-of select="context/correlation/lastRequestedOn"/>
              </xsl:element>
            </xsl:if>
          </transactionLogRequest>
        </out:updateGCTransactionLog>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:GCTransactionLogRequestMap_req_12">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:updateGCTransactionLogRequestMsg'"/>
      </xsl:attribute>
      <out:updateGCTransactionLog>
        <transactionLogRequest>
          <!-- a simple data mapping: "$smo/context/correlation/transactionId"(int) to "transactionId"(int) -->
          <xsl:if test="$smo/context/correlation/transactionId">
            <xsl:element name="transactionId">
              <xsl:value-of select="$smo/context/correlation/transactionId"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/context/correlation/request"(string) to "request"(string) -->
          <xsl:if test="$smo/context/correlation/request">
            <xsl:element name="request">
              <xsl:value-of select="$smo/context/correlation/request"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/context/correlation/isExecuting"(int) to "isExecuting"(int) -->
          <xsl:if test="$smo/context/correlation/isExecuting">
            <xsl:element name="isExecuting">
              <xsl:value-of select="$smo/context/correlation/isExecuting"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/context/correlation/lastRequestedOn"(dateTime) to "lastRequestedOn"(dateTime) -->
          <xsl:if test="$smo/context/correlation/lastRequestedOn">
            <xsl:element name="lastRequestedOn">
              <xsl:value-of select="$smo/context/correlation/lastRequestedOn"/>
            </xsl:element>
          </xsl:if>
        </transactionLogRequest>
      </out:updateGCTransactionLog>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
