<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/getCDDetailsOutputMap.map" md5sum="36f30904be9b2938961fe4db7cc2b005" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		getCDDetailsOutputMap.map
*   Map declaration(s):	getCDDetailsOutputMap
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DgetDetailsOfCDRefundResponse/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DfindCDDetailsResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in2="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:in="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out3="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out2="http://RACASBO"
    xmlns:out5="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out4="http://GCLibrary/org/aig/access/BO"
    xmlns:out="http://GCLibrary/org/aig/access/bo"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/getCDDetailsOutputMap"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out3:findCDDetailsResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:getCDDetailsOutputMap2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:getCDDetailsOutputMap">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:getCDDetailsOutputMap">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:findCDDetailsResponseMsg'"/>
      </xsl:attribute>
      <out5:findCDDetailsResponse>
        <CDDetails>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_TYPE"(string) to "out2:CDPartnerType"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_TYPE">
            <xsl:element name="out2:CDPartnerType">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_TYPE"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_BALANCE"(string) to "out2:CDBalance"(double) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_BALANCE">
            <xsl:element name="out2:CDBalance">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_BALANCE"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_ID"(string) to "out2:CDPartnerId"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_ID">
            <xsl:element name="out2:CDPartnerId">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_ID"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_NAME"(string) to "out2:CDPartnerName"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_NAME">
            <xsl:element name="out2:CDPartnerName">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_NAME"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_FROM"(string) to "out2:CDValidityFrom"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_FROM">
            <xsl:element name="out2:CDValidityFrom">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_FROM"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_TO"(string) to "out2:CDValidaityTo"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_TO">
            <xsl:element name="out2:CDValidaityTo">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_TO"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/EMAIL_ID_CLIENT"(string) to "out2:EmailIDOfClient"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/EMAIL_ID_CLIENT">
            <xsl:element name="out2:EmailIDOfClient">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/EMAIL_ID_CLIENT"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/NAME_OF_REQUESTOR"(string) to "out2:NameOfRequestor"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/NAME_OF_REQUESTOR">
            <xsl:element name="out2:NameOfRequestor">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/NAME_OF_REQUESTOR"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CHANNEL_OF_REQUESTOR"(string) to "out2:ChannelOfRequestor"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CHANNEL_OF_REQUESTOR">
            <xsl:element name="out2:ChannelOfRequestor">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CHANNEL_OF_REQUESTOR"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_STATUS"(string) to "out2:CDStatus"(string) -->
          <xsl:if test="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_STATUS">
            <xsl:element name="out2:CDStatus">
              <xsl:value-of select="in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_STATUS"/>
            </xsl:element>
          </xsl:if>
        </CDDetails>
      </out5:findCDDetailsResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:getCDDetailsOutputMap2">
    <xsl:param name="body"/>
    <out5:findCDDetailsResponse>
      <CDDetails>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_TYPE"(string) to "out2:CDPartnerType"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_TYPE">
          <xsl:element name="out2:CDPartnerType">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_TYPE"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_BALANCE"(string) to "out2:CDBalance"(double) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_BALANCE">
          <xsl:element name="out2:CDBalance">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_BALANCE"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_ID"(string) to "out2:CDPartnerId"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_ID">
          <xsl:element name="out2:CDPartnerId">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_ID"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_NAME"(string) to "out2:CDPartnerName"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_NAME">
          <xsl:element name="out2:CDPartnerName">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_PARTNER_NAME"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_FROM"(string) to "out2:CDValidityFrom"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_FROM">
          <xsl:element name="out2:CDValidityFrom">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_FROM"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_TO"(string) to "out2:CDValidaityTo"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_TO">
          <xsl:element name="out2:CDValidaityTo">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_VALIDITY_TO"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/EMAIL_ID_CLIENT"(string) to "out2:EmailIDOfClient"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/EMAIL_ID_CLIENT">
          <xsl:element name="out2:EmailIDOfClient">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/EMAIL_ID_CLIENT"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/NAME_OF_REQUESTOR"(string) to "out2:NameOfRequestor"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/NAME_OF_REQUESTOR">
          <xsl:element name="out2:NameOfRequestor">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/NAME_OF_REQUESTOR"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CHANNEL_OF_REQUESTOR"(string) to "out2:ChannelOfRequestor"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CHANNEL_OF_REQUESTOR">
          <xsl:element name="out2:ChannelOfRequestor">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CHANNEL_OF_REQUESTOR"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_STATUS"(string) to "out2:CDStatus"(string) -->
        <xsl:if test="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_STATUS">
          <xsl:element name="out2:CDStatus">
            <xsl:value-of select="$body/in2:getDetailsOfCDRefundResponse/in2:GetDetailsOfCDRefundResult/GetDetailsOfCDRefundData[1]/CD_STATUS"/>
          </xsl:element>
        </xsl:if>
      </CDDetails>
    </out5:findCDDetailsResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
