<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/KhokhaPremiumOutputMap.map" md5sum="7598c5c837b4422669f8a26e905d228e" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		KhokhaPremiumOutputMap.map
*   Map declaration(s):	KhokhaPremiumOutputMap
*   Input file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252Fstub.unotechsoft.com%252Fwsdl%252FRASRefundCancellationKhoka%252F%257DwebServiceRASGenericPremiumCalculationResponse/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/correlationContext%3D%257Bhttp%253A%252F%252FAccess-ApplicationGC%257DcorrelationBO/message%3D%257Bhttp%253A%252F%252Fstub.unotechsoft.com%252Fwsdl%252FRASMotor%252F%257DwebServicePremiumCalculationDtlsResponse/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://Access-ApplicationGC"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in="http://stub.unotechsoft.com/wsdl/RASRefundCancellationKhoka/"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:in2="wsdl.http://stub.unotechsoft.com/wsdl/RASRefundCancellationKhoka/"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="WebService_RefundCancellationDtls"
    xmlns:out3="wsdl.http://stub.unotechsoft.com/wsdl/RASMotor/"
    xmlns:out="http://stub.unotechsoft.com/wsdl/RASMotor/"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/KhokhaPremiumOutputMap"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io4:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:KhokhaPremiumOutputMap2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io4:smo" mode="map:KhokhaPremiumOutputMap">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io4:smo" to "io4:smo".  -->
  <xsl:template match="io4:smo"  mode="map:KhokhaPremiumOutputMap">
    <io4:smo>
      <context>
        <!-- a structural mapping: "context/correlation"(correlationBO) to "correlation"(correlationBO) -->
        <xsl:if test="context/correlation">
          <xsl:copy-of select="context/correlation"/>
        </xsl:if>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out3:webServicePremiumCalculationDtlsResponse'"/>
        </xsl:attribute>
        <out:webServicePremiumCalculationDtlsResponse>
          <out:WebService_PremiumCalculationDtlsResult>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oNetPremium"(string) to "out2:NetPremium"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oNetPremium">
              <xsl:element name="out2:NetPremium">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oNetPremium"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oGst"(string) to "out2:GST"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oGst">
              <xsl:element name="out2:GST">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oGst"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oJkgst"(string) to "out2:JKGST"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oJkgst">
              <xsl:element name="out2:JKGST">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oJkgst"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStampDuty"(string) to "out2:StampDuty"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStampDuty">
              <xsl:element name="out2:StampDuty">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStampDuty"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oTotalPremium"(string) to "out2:TotalPremium"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oTotalPremium">
              <xsl:element name="out2:TotalPremium">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oTotalPremium"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStatus"(string) to "out2:Status"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStatus">
              <xsl:element name="out2:Status">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStatus"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorCode"(string) to "out2:ErrorID"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorCode">
              <xsl:element name="out2:ErrorID">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorCode"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple data mapping: "body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorDesc"(string) to "out2:ErrorDesc"(string) -->
            <xsl:if test="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorDesc">
              <xsl:element name="out2:ErrorDesc">
                <xsl:value-of select="body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorDesc"/>
              </xsl:element>
            </xsl:if>
          </out:WebService_PremiumCalculationDtlsResult>
        </out:webServicePremiumCalculationDtlsResponse>
      </body>
    </io4:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io4:smo" to "io4:smo".  -->
  <xsl:template name="map:KhokhaPremiumOutputMap2">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/context/correlation"(correlationBO) to "correlation"(correlationBO) -->
      <xsl:if test="$smo/context/correlation">
        <xsl:copy-of select="$smo/context/correlation"/>
      </xsl:if>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:webServicePremiumCalculationDtlsResponse'"/>
      </xsl:attribute>
      <out:webServicePremiumCalculationDtlsResponse>
        <out:WebService_PremiumCalculationDtlsResult>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oNetPremium"(string) to "out2:NetPremium"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oNetPremium">
            <xsl:element name="out2:NetPremium">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oNetPremium"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oGst"(string) to "out2:GST"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oGst">
            <xsl:element name="out2:GST">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oGst"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oJkgst"(string) to "out2:JKGST"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oJkgst">
            <xsl:element name="out2:JKGST">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oJkgst"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStampDuty"(string) to "out2:StampDuty"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStampDuty">
            <xsl:element name="out2:StampDuty">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStampDuty"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oTotalPremium"(string) to "out2:TotalPremium"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oTotalPremium">
            <xsl:element name="out2:TotalPremium">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oTotalPremium"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStatus"(string) to "out2:Status"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStatus">
            <xsl:element name="out2:Status">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oStatus"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorCode"(string) to "out2:ErrorID"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorCode">
            <xsl:element name="out2:ErrorID">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorCode"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorDesc"(string) to "out2:ErrorDesc"(string) -->
          <xsl:if test="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorDesc">
            <xsl:element name="out2:ErrorDesc">
              <xsl:value-of select="$smo/body/in:webServiceRASGenericPremiumCalculationResponse/in:WebService_RASGenericPremiumCalculationResult/oErrorDesc"/>
            </xsl:element>
          </xsl:if>
        </out:WebService_PremiumCalculationDtlsResult>
      </out:webServicePremiumCalculationDtlsResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
