<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/Mapping_res_1.map" md5sum="9c43f051fcc1a9a28805f04613eccf5a" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		Mapping_res_1.map
*   Map declaration(s):	Mapping_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DfetchCDDetailsRASResponse/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DfindCdDetailsAcc_findCdDetailsAccFaultMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in6="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:io6="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:in5="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:in="WebService_AccRefundRequest"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in2="http://stub.tagicesb.com/wsdl/RASHealthService/"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io5="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in4="WebService_RefundCancellationDtls"
    xmlns:io4="http://www.w3.org/2005/08/addressing"
    xmlns:in3="WebService_RefundDetails"
    xmlns:out2="http://RACASBO"
    xmlns:out3="http://GCLibrary/org/aig/access/BO"
    xmlns:out4="http://GCLibrary/org/aig/access/bo"
    xmlns:out5="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:out="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/Mapping_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out5:findCdDetailsAcc_findCdDetailsAccFaultMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:Mapping_res_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:Mapping_res_1">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:Mapping_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out5:findCdDetailsAcc_findCdDetailsAccFaultMsg'"/>
      </xsl:attribute>
      <out:findCdDetailsAccFault1_findCdDetailsAccFault>
        <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
        <xsl:element name="out2:status">
          <xsl:text>FAILED</xsl:text>
        </xsl:element>
        <out2:error>
          <!-- a simple mapping with no associated source:  to "out2:message"(string) -->
          <xsl:element name="out2:message">
            <xsl:text>No Data Found</xsl:text>
          </xsl:element>
        </out2:error>
      </out:findCdDetailsAccFault1_findCdDetailsAccFault>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:Mapping_res_12">
    <xsl:param name="body"/>
    <out:findCdDetailsAccFault1_findCdDetailsAccFault>
      <!-- a simple mapping with no associated source:  to "out2:status"(string) -->
      <xsl:element name="out2:status">
        <xsl:text>FAILED</xsl:text>
      </xsl:element>
      <out2:error>
        <!-- a simple mapping with no associated source:  to "out2:message"(string) -->
        <xsl:element name="out2:message">
          <xsl:text>No Data Found</xsl:text>
        </xsl:element>
      </out2:error>
    </out:findCdDetailsAccFault1_findCdDetailsAccFault>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
