<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/TenureDetailsInputMap.map" md5sum="27b208777c86353eb8ce6ce0c8781b21" version="8.0.501" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		TenureDetailsInputMap.map
*   Map declaration(s):	TenureDetailsInputMap
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FGCDomain-v1.0.0%252Forg%252Ftataaig%252Faccess%252FRetrieveAccessGC%257DtenureDetailsRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fstub.tagicesb.com%252Fwsdl%252FRASGenericService%252F%257DtenureDetails/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:in5="wsdl.http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:in="http://GCDomain-v1.0.0/org/tataaig/access/RetrieveAccessGC"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in2="http://RACASBO"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in4="http://GCLibrary/org/aig/access/BO"
    xmlns:io5="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in3="http://GCLibrary/org/aig/access/bo"
    xmlns:io4="http://www.w3.org/2005/08/addressing"
    xmlns:out2="http://stub.tagicesb.com/wsdl/RASHealthService/"
    xmlns:out3="WebService_RefundDetails"
    xmlns:out4="WebService_RefundCancellationDtls"
    xmlns:out5="http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:out6="wsdl.http://stub.tagicesb.com/wsdl/RASGenericService/"
    xmlns:out="WebService_AccRefundRequest"
    xmlns:map="http://RASAccess-ApplicationGC/xslt/TenureDetailsInputMap"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out6:tenureDetails'"/>
            </xsl:attribute>
            <xsl:call-template name="map:TenureDetailsInputMap2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:TenureDetailsInputMap">
        </xsl:apply-templates>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:TenureDetailsInputMap">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out6:tenureDetails'"/>
      </xsl:attribute>
      <out5:tenureDetails>
        <!-- a simple data mapping: "in:tenureDetails/GCInputs/source"(string) to "out5:source"(string) -->
        <xsl:if test="in:tenureDetails/GCInputs/source">
          <xsl:element name="out5:source">
            <xsl:value-of select="in:tenureDetails/GCInputs/source"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in:tenureDetails/GCInputs/medium"(string) to "out5:medium"(string) -->
        <xsl:if test="in:tenureDetails/GCInputs/medium">
          <xsl:element name="out5:medium">
            <xsl:value-of select="in:tenureDetails/GCInputs/medium"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in:tenureDetails/GCInputs/campaign"(string) to "out5:campaign"(string) -->
        <xsl:if test="in:tenureDetails/GCInputs/campaign">
          <xsl:element name="out5:campaign">
            <xsl:value-of select="in:tenureDetails/GCInputs/campaign"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in:tenureDetails/proposalNumber"(string) to "out5:ProposalNo"(string) -->
        <xsl:if test="in:tenureDetails/proposalNumber">
          <xsl:element name="out5:ProposalNo">
            <xsl:value-of select="in:tenureDetails/proposalNumber"/>
          </xsl:element>
        </xsl:if>
      </out5:tenureDetails>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:TenureDetailsInputMap2">
    <xsl:param name="body"/>
    <out5:tenureDetails>
      <!-- a simple data mapping: "$body/in:tenureDetails/GCInputs/source"(string) to "out5:source"(string) -->
      <xsl:if test="$body/in:tenureDetails/GCInputs/source">
        <xsl:element name="out5:source">
          <xsl:value-of select="$body/in:tenureDetails/GCInputs/source"/>
        </xsl:element>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:tenureDetails/GCInputs/medium"(string) to "out5:medium"(string) -->
      <xsl:if test="$body/in:tenureDetails/GCInputs/medium">
        <xsl:element name="out5:medium">
          <xsl:value-of select="$body/in:tenureDetails/GCInputs/medium"/>
        </xsl:element>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:tenureDetails/GCInputs/campaign"(string) to "out5:campaign"(string) -->
      <xsl:if test="$body/in:tenureDetails/GCInputs/campaign">
        <xsl:element name="out5:campaign">
          <xsl:value-of select="$body/in:tenureDetails/GCInputs/campaign"/>
        </xsl:element>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:tenureDetails/proposalNumber"(string) to "out5:ProposalNo"(string) -->
      <xsl:if test="$body/in:tenureDetails/proposalNumber">
        <xsl:element name="out5:ProposalNo">
          <xsl:value-of select="$body/in:tenureDetails/proposalNumber"/>
        </xsl:element>
      </xsl:if>
    </out5:tenureDetails>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
