<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="rashealthservice_wsdl_Endpoint" targetNamespace="http://stub.tagicesb.com/wsdl/RASHealthService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://stub.tagicesb.com/wsdl/RASHealthService/">
    <wsdl:import location="rashealthservice_wsdl.wsdl" namespace="http://stub.tagicesb.com/wsdl/RASHealthService/"/>
  <wsdl:binding name="RASHealthServiceSoapBinding" type="tns:RASHealthService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="webServiceRefundCancellationHealth">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="webServiceRefundCancellationHealth">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="webServiceRefundCancellationHealthResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="webServicePremiumCalculationHealth">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="webServicePremiumCalculationHealth">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="webServicePremiumCalculationHealthResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RASHealthService">
    <wsdl:port binding="tns:RASHealthServiceSoapBinding" name="SOAPOverHTTP">
      <soap:address location="http://172.20.251.126:8182/cxf/RASHealthService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>