<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="rasltaservice_wsdl_Endpoint" targetNamespace="http://stub.unotechsoft.com/wsdl/RASLTAService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://stub.unotechsoft.com/wsdl/RASLTAService/">
    <wsdl:import location="rasltaservice_wsdl.wsdl" namespace="http://stub.unotechsoft.com/wsdl/RASLTAService/"/>
  <wsdl:binding name="RASLTAServiceSoapBinding" type="tns:RASLTAService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="webServicePremiumCalculationLTA">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="webServicePremiumCalculationLTA">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="webServicePremiumCalculationLTAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="webServiceRefundCancellationLTA">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="webServiceRefundCancellationLTA">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="webServiceRefundCancellationLTAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RASLTAService">
    <wsdl:port binding="tns:RASLTAServiceSoapBinding" name="SOAPOverHTTP">
      <soap:address location="http://172.20.251.126:8182/cxf/RASLTAService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>